CREATE DATABASE IF NOT EXISTS vrp_research;
USE vrp_research;

CREATE TABLE IF NOT EXISTS DATASET (
    DATASET_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    DATASET_CODE VARCHAR(50),
    DATASET_NAME VARCHAR(100),
    DATASET_TYPE VARCHAR(50),
    SOURCE_TYPE VARCHAR(50),
    SOURCE_REFERENCE VARCHAR(200),
    CUSTOMER_COUNT INT,
    VEHICLE_COUNT INT,
    DEPOT_COUNT INT,
    DISTANCE_TYPE VARCHAR(50),
    TIME_DEPENDENT BOOLEAN,
    VERSION_NO VARCHAR(20),
    CHECKSUM VARCHAR(100),
    CREATED_DATE DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS DEPOT (
    DEPOT_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    DATASET_ID BIGINT,
    DEPOT_CODE VARCHAR(50),
    DEPOT_NAME VARCHAR(100),
    LATITUDE DOUBLE,
    LONGITUDE DOUBLE,
    OPEN_TIME INT,
    CLOSE_TIME INT,
    FOREIGN KEY (DATASET_ID) REFERENCES DATASET(DATASET_ID)
);

CREATE TABLE IF NOT EXISTS CUSTOMER (
    CUSTOMER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    DATASET_ID BIGINT,
    CUSTOMER_CODE VARCHAR(50),
    CUSTOMER_NAME VARCHAR(100),
    LATITUDE DOUBLE,
    LONGITUDE DOUBLE,
    SERVICE_TIME INT,
    TIME_WINDOW_START INT,
    TIME_WINDOW_END INT,
    PRIORITY INT,
    DELIVERY_ORDER INT,
    FOREIGN KEY (DATASET_ID) REFERENCES DATASET(DATASET_ID)
);

CREATE TABLE IF NOT EXISTS ORDERS (
    ORDER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    DATASET_ID BIGINT,
    CUSTOMER_ID BIGINT,
    ORDER_CODE VARCHAR(50),
    DEMAND_WEIGHT DOUBLE,
    DEMAND_VOLUME DOUBLE,
    READY_TIME INT,
    DUE_TIME INT,
    SERVICE_TIME INT,
    REQUIRED_VEHICLE_TYPE VARCHAR(50),
    STATUS VARCHAR(50),
    FOREIGN KEY (DATASET_ID) REFERENCES DATASET(DATASET_ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
);

CREATE TABLE IF NOT EXISTS VEHICLE (
    VEHICLE_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    DATASET_ID BIGINT,
    VEHICLE_CODE VARCHAR(50),
    CAPACITY_WEIGHT DOUBLE,
    CAPACITY_VOLUME DOUBLE,
    START_DEPOT_ID BIGINT,
    END_DEPOT_ID BIGINT,
    AVAILABLE_FROM INT,
    AVAILABLE_TO INT,
    FIXED_COST DOUBLE,
    COST_PER_KM DOUBLE,
    COST_PER_MINUTE DOUBLE,
    FOREIGN KEY (DATASET_ID) REFERENCES DATASET(DATASET_ID),
    FOREIGN KEY (START_DEPOT_ID) REFERENCES DEPOT(DEPOT_ID),
    FOREIGN KEY (END_DEPOT_ID) REFERENCES DEPOT(DEPOT_ID)
);

CREATE TABLE IF NOT EXISTS DRIVER (
    DRIVER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    DATASET_ID BIGINT,
    DRIVER_CODE VARCHAR(50),
    VEHICLE_ID BIGINT,
    SHIFT_START INT,
    SHIFT_END INT,
    MAX_WORKING_TIME INT,
    FOREIGN KEY (DATASET_ID) REFERENCES DATASET(DATASET_ID),
    FOREIGN KEY (VEHICLE_ID) REFERENCES VEHICLE(VEHICLE_ID)
);

CREATE TABLE IF NOT EXISTS LOCATION_DISTANCE (
    DATASET_ID BIGINT,
    FROM_LOCATION_ID BIGINT,
    TO_LOCATION_ID BIGINT,
    DISTANCE DOUBLE,
    BASE_TRAVEL_TIME DOUBLE,
    PRIMARY KEY (DATASET_ID, FROM_LOCATION_ID, TO_LOCATION_ID),
    FOREIGN KEY (DATASET_ID) REFERENCES DATASET(DATASET_ID)
);

CREATE TABLE IF NOT EXISTS TRAVEL_TIME_PROFILE (
    PROFILE_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    DATASET_ID BIGINT,
    FROM_LOCATION_ID BIGINT,
    TO_LOCATION_ID BIGINT,
    START_TIME INT,
    END_TIME INT,
    TRAVEL_TIME DOUBLE,
    SPEED_FACTOR DOUBLE,
    TRAFFIC_LEVEL VARCHAR(50),
    FOREIGN KEY (DATASET_ID) REFERENCES DATASET(DATASET_ID)
);

CREATE TABLE IF NOT EXISTS ALGORITHM (
    ALGORITHM_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ALGORITHM_CODE VARCHAR(50),
    ALGORITHM_NAME VARCHAR(100),
    ALGORITHM_VERSION VARCHAR(50),
    DESCRIPTION TEXT,
    SOURCE_REFERENCE VARCHAR(200)
);

CREATE TABLE IF NOT EXISTS ALGORITHM_PARAMETER (
    PARAMETER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ALGORITHM_ID BIGINT,
    PARAMETER_CODE VARCHAR(50),
    PARAMETER_NAME VARCHAR(100),
    DATA_TYPE VARCHAR(50),
    DEFAULT_VALUE VARCHAR(100),
    MIN_VALUE VARCHAR(100),
    MAX_VALUE VARCHAR(100),
    DESCRIPTION TEXT,
    FOREIGN KEY (ALGORITHM_ID) REFERENCES ALGORITHM(ALGORITHM_ID)
);

CREATE TABLE IF NOT EXISTS EXPERIMENT (
    EXPERIMENT_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    EXPERIMENT_CODE VARCHAR(100),
    DATASET_ID BIGINT,
    ALGORITHM_ID BIGINT,
    OBJECTIVE_TYPE VARCHAR(50),
    TIME_LIMIT INT,
    ITERATION_LIMIT INT,
    RANDOM_SEED BIGINT,
    MACHINE_INFO VARCHAR(200),
    START_TIME DATETIME,
    END_TIME DATETIME,
    STATUS VARCHAR(50),
    FOREIGN KEY (DATASET_ID) REFERENCES DATASET(DATASET_ID),
    FOREIGN KEY (ALGORITHM_ID) REFERENCES ALGORITHM(ALGORITHM_ID)
);

CREATE TABLE IF NOT EXISTS EXPERIMENT_PARAMETER_VALUE (
    EXPERIMENT_ID BIGINT,
    PARAMETER_ID BIGINT,
    PARAMETER_VALUE VARCHAR(100),
    PRIMARY KEY (EXPERIMENT_ID, PARAMETER_ID),
    FOREIGN KEY (EXPERIMENT_ID) REFERENCES EXPERIMENT(EXPERIMENT_ID),
    FOREIGN KEY (PARAMETER_ID) REFERENCES ALGORITHM_PARAMETER(PARAMETER_ID)
);

CREATE TABLE IF NOT EXISTS EXPERIMENT_RESULT (
    RESULT_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    EXPERIMENT_ID BIGINT,
    TOTAL_DISTANCE DOUBLE,
    TOTAL_TRAVEL_TIME DOUBLE,
    TOTAL_WAITING_TIME DOUBLE,
    TOTAL_SERVICE_TIME DOUBLE,
    VEHICLE_USED INT,
    UNSERVED_ORDER_COUNT INT,
    CAPACITY_VIOLATION DOUBLE,
    TIME_WINDOW_VIOLATION DOUBLE,
    OBJECTIVE_VALUE DOUBLE,
    EXECUTION_TIME_MS BIGINT,
    ITERATION_FOUND INT,
    IS_FEASIBLE BOOLEAN,
    FOREIGN KEY (EXPERIMENT_ID) REFERENCES EXPERIMENT(EXPERIMENT_ID)
);

CREATE TABLE IF NOT EXISTS ROUTE_RESULT (
    ROUTE_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    RESULT_ID BIGINT,
    VEHICLE_ID BIGINT,
    ROUTE_NO INT,
    TOTAL_DISTANCE DOUBLE,
    TOTAL_TIME DOUBLE,
    TOTAL_LOAD DOUBLE,
    START_TIME INT,
    END_TIME INT,
    FOREIGN KEY (RESULT_ID) REFERENCES EXPERIMENT_RESULT(RESULT_ID),
    FOREIGN KEY (VEHICLE_ID) REFERENCES VEHICLE(VEHICLE_ID)
);

CREATE TABLE IF NOT EXISTS ROUTE_STOP_RESULT (
    ROUTE_STOP_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ROUTE_ID BIGINT,
    SEQUENCE_NO INT,
    LOCATION_ID BIGINT,
    ORDER_ID BIGINT,
    ARRIVAL_TIME DOUBLE,
    SERVICE_START_TIME DOUBLE,
    DEPARTURE_TIME DOUBLE,
    WAITING_TIME DOUBLE,
    LOAD_BEFORE DOUBLE,
    LOAD_AFTER DOUBLE,
    TRAVEL_DISTANCE DOUBLE,
    TRAVEL_TIME DOUBLE,
    FOREIGN KEY (ROUTE_ID) REFERENCES ROUTE_RESULT(ROUTE_ID),
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID)
);

-- Insert demo dataset to avoid errors in Main.java
INSERT INTO DATASET (DATASET_ID, DATASET_CODE, DATASET_TYPE, CUSTOMER_COUNT, VEHICLE_COUNT) 
VALUES (1, 'DEMO_01', 'CVRP', 5, 2)
ON DUPLICATE KEY UPDATE DATASET_CODE='DEMO_01';
