package vn.vrp.db;
import vn.vrp.model.*; import vn.vrp.validator.ValidationResult; import java.sql.*; import java.time.*;
public final class ExperimentDao {
    public long save(Connection c,ProblemInstance p,Solution s,ValidationResult validation,long seed)throws SQLException{boolean old=c.getAutoCommit();c.setAutoCommit(false);try{long algorithmId=findAlgorithm(c);long experimentId=insertExperiment(c,p,seed,algorithmId);long resultId=insertResult(c,experimentId,s,validation);int no=1;for(Route r:s.routes())insertRoute(c,resultId,no++,r);try(var ps=c.prepareStatement("UPDATE experiment SET end_time=NOW(),status='COMPLETED' WHERE experiment_id=?")){ps.setLong(1,experimentId);ps.executeUpdate();}c.commit();return experimentId;}catch(Exception e){c.rollback();if(e instanceof SQLException sql)throw sql;throw new SQLException(e);}finally{c.setAutoCommit(old);}}
    private long findAlgorithm(Connection c)throws SQLException{try(var ps=c.prepareStatement("SELECT algorithm_id FROM algorithm WHERE algorithm_code='BASELINE_SEQUENTIAL_INSERTION'" );var rs=ps.executeQuery()){if(!rs.next())throw new SQLException("Thiếu algorithm BASELINE_SEQUENTIAL_INSERTION");return rs.getLong(1);}}
    private long insertExperiment(Connection c,ProblemInstance p,long seed,long algorithmId)throws SQLException{String code="EXP_GREEDY_"+p.datasetId()+"_"+System.currentTimeMillis();String q="INSERT INTO experiment(experiment_code,dataset_id,algorithm_id,random_seed,machine_info,start_time,status,notes) VALUES(?,?,?,?,?,NOW(),'RUNNING',?)";try(var ps=c.prepareStatement(q,Statement.RETURN_GENERATED_KEYS)){ps.setString(1,code);ps.setLong(2,p.datasetId());ps.setLong(3,algorithmId);ps.setLong(4,seed);ps.setString(5,System.getProperty("os.name")+"; Java "+System.getProperty("java.version"));ps.setString(6,"Greedy nearest-neighbor CVRP console demo");ps.executeUpdate();return key(ps);}}
    private long insertResult(Connection c,long experimentId,Solution s,ValidationResult v)throws SQLException{String q="INSERT INTO experiment_result(experiment_id,total_distance,total_travel_time,total_waiting_time,total_service_time,vehicle_used,unserved_order_count,capacity_violation,time_window_violation,objective_value,execution_time_ms,is_feasible) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)";try(var ps=c.prepareStatement(q,Statement.RETURN_GENERATED_KEYS)){int i=1;ps.setLong(i++,experimentId);ps.setDouble(i++,s.totalDistance());ps.setInt(i++,s.totalTravelTime());ps.setInt(i++,s.totalWaitingTime());ps.setInt(i++,s.totalServiceTime());ps.setInt(i++,s.routes().size());ps.setInt(i++,v.unservedOrders());ps.setDouble(i++,v.capacityViolation());ps.setInt(i++,v.timeWindowViolation());ps.setDouble(i++,s.routes().size()*100000d+s.totalDistance());ps.setLong(i++,s.executionTimeMs());ps.setBoolean(i,v.valid());ps.executeUpdate();return key(ps);}}
    private void insertRoute(Connection c,long resultId,int no,Route r)throws SQLException{String q="INSERT INTO route_result(result_id,vehicle_id,route_no,total_distance,total_travel_time,total_waiting_time,total_service_time,total_load_weight,total_load_volume,start_time,end_time,is_feasible) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)";long routeId;try(var ps=c.prepareStatement(q,Statement.RETURN_GENERATED_KEYS)){int i=1;ps.setLong(i++,resultId);ps.setLong(i++,r.vehicle().id());ps.setInt(i++,no);ps.setDouble(i++,r.totalDistance());ps.setInt(i++,r.totalTravelTime());ps.setInt(i++,r.totalWaitingTime());ps.setInt(i++,r.totalServiceTime());ps.setDouble(i++,r.totalLoadWeight());ps.setDouble(i++,r.totalLoadVolume());ps.setInt(i++,r.startTime());ps.setInt(i++,r.endTime());ps.setBoolean(i,r.feasible());ps.executeUpdate();routeId=key(ps);}int seq=0;for(RouteStop x:r.stops())insertStop(c,routeId,seq++,x);}
    private void insertStop(Connection c,long routeId,int seq,RouteStop x)throws SQLException{String q="INSERT INTO route_stop_result(route_id,sequence_no,stop_type,location_id,order_id,arrival_time,service_start_time,departure_time,waiting_time,service_time,demand_weight,demand_volume,load_before_weight,load_after_weight,load_before_volume,load_after_volume,travel_distance,travel_time,capacity_violation,time_window_violation) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";try(var ps=c.prepareStatement(q)){int i=1;ps.setLong(i++,routeId);ps.setInt(i++,seq);ps.setString(i++,x.type().name());ps.setLong(i++,x.locationId());if(x.orderId()==null)ps.setNull(i++,Types.BIGINT);else ps.setLong(i++,x.orderId());ps.setInt(i++,x.arrivalTime());ps.setInt(i++,x.serviceStartTime());ps.setInt(i++,x.departureTime());ps.setInt(i++,x.waitingTime());ps.setInt(i++,x.serviceTime());ps.setDouble(i++,x.demandWeight());ps.setDouble(i++,x.demandVolume());ps.setDouble(i++,x.loadBeforeWeight());ps.setDouble(i++,x.loadAfterWeight());ps.setDouble(i++,x.loadBeforeVolume());ps.setDouble(i++,x.loadAfterVolume());ps.setDouble(i++,x.travelDistance());ps.setInt(i++,x.travelTime());ps.setDouble(i++,x.capacityViolation());ps.setInt(i,x.timeWindowViolation());ps.executeUpdate();}}
    private long key(PreparedStatement ps)throws SQLException{try(var rs=ps.getGeneratedKeys()){if(!rs.next())throw new SQLException("Không nhận được generated key");return rs.getLong(1);}}
}
